# Generated by Django 5.2.1 on 2025-11-27 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techfeed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="techcommentaire",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentaires",
                to="techfeed.techvideo",
            ),
        ),
    ]
