# Generated by Django 5.2.1 on 2025-11-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techfeed", "0004_techmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="techmessage",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_attachments/"
            ),
        ),
        migrations.AlterField(
            model_name="techmessage",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
