# Generated by Django 5.2.1 on 2025-11-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techfeed", "0007_profile_is_live_technotification_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="techgroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
