# Generated by Django 5.2.1 on 2025-12-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techfeed", "0011_callsession_technotification_call_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="callsession",
            name="call_type",
            field=models.CharField(
                choices=[("audio", "Audio"), ("video", "Vidéo")],
                default="video",
                max_length=10,
            ),
        ),
    ]
