# Generated by Django 5.2.1 on 2025-12-21 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techfeed", "0013_groupcallsession_technotification_group_call_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesession",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="live_sessions",
                to="techfeed.techgroup",
            ),
        ),
    ]
