# Generated by Django 5.2.1 on 2025-12-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techfeed", "0014_livesession_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupcallsession",
            name="call_type",
            field=models.CharField(
                choices=[("audio", "Audio"), ("video", "Vidéo")],
                default="audio",
                max_length=10,
            ),
        ),
    ]
