# Generated by Django 5.2.1 on 2025-12-22 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techfeed", "0015_alter_groupcallsession_call_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="techcommentaire",
            options={"ordering": ["date_pub"]},
        ),
        migrations.AddField(
            model_name="techcommentaire",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reponses",
                to="techfeed.techcommentaire",
            ),
        ),
    ]
