# Generated by Django 5.2.1 on 2025-12-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("techfeed", "0016_alter_techcommentaire_options_techcommentaire_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="techcommentaire",
            options={},
        ),
    ]
