# Generated by Django 5.2.1 on 2025-12-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("techfeed", "0017_alter_techcommentaire_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="techcommentaire",
            options={"ordering": ["date_pub"]},
        ),
    ]
