# Generated by Django 5.2.1 on 2025-11-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monetisation", "0005_alter_referral_code_alter_referral_referrer"),
    ]

    operations = [
        migrations.AddField(
            model_name="referraltransaction",
            name="converted",
            field=models.BooleanField(default=False),
        ),
    ]
