# Generated by Django 5.2.15 on 2026-08-16 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetisation', '0006_referraltransaction_converted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('owner_name', models.CharField(help_text='Nom du titulaire du compte, affiche au client', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('instructions', models.CharField(blank=True, help_text='Instructions optionnelles affichees au client', max_length=255)),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests_reviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
