# Generated by Django 5.2.15 on 2026-08-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetisation', '0007_mobilemoneyaccount_paymentrequest_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='amount_local',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='currency_local',
            field=models.CharField(default='GNF', max_length=3),
        ),
    ]
