# Generated by Django 5.2.1 on 2025-12-18 23:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("resume", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Université", "Université"),
                            ("Entreprise", "Entreprise"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parcours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("Débutant", "Débutant"),
                            ("Intermédiaire", "Intermédiaire"),
                            ("Avancé", "Avancé"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prix",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("certifiant", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BlocPedagogique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("texte", "Texte"),
                            ("image", "Image"),
                            ("video", "Vidéo"),
                            ("code", "Code"),
                            ("quiz", "Quiz"),
                            ("exercice", "Exercice"),
                            ("simulation", "Simulation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contenu", models.TextField(blank=True, null=True)),
                (
                    "media_file",
                    models.FileField(blank=True, null=True, upload_to="blocs/"),
                ),
                ("language", models.CharField(blank=True, max_length=30, null=True)),
                ("code", models.TextField(blank=True, null=True)),
                (
                    "lecon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocs",
                        to="iot.lecon",
                    ),
                ),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
        migrations.AddField(
            model_name="lecon",
            name="parcours",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecons",
                to="iot.parcours",
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="projects/videos/"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="projects/images/"
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=30, null=True)),
                ("code", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parcours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="iot.parcours",
                    ),
                ),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("choix_a", models.CharField(max_length=255)),
                ("choix_b", models.CharField(max_length=255)),
                ("choix_c", models.CharField(blank=True, max_length=255, null=True)),
                ("choix_d", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bonne_reponse",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
                ("explication", models.TextField(blank=True, null=True)),
                (
                    "lecon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="iot.lecon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_final", models.FloatField()),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="certificats/"),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="certificats/qrcodes/"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parcours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iot.parcours"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "parcours"),
                        name="unique_certification_per_user_parcours",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Progression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("score", models.FloatField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iot.lecon"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "lecon")},
            },
        ),
    ]
