# Generated by Django 5.2.1 on 2025-12-19 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="couleur_principale",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organisation",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="organisations/logos/"
            ),
        ),
        migrations.AddField(
            model_name="parcours",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcours_crees",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parcours",
            name="organisation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parcours",
                to="iot.organisation",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blocpedagogique",
            name="type",
            field=models.CharField(
                choices=[
                    ("texte", "Texte"),
                    ("image", "Image"),
                    ("video", "Vidéo"),
                    ("code", "Code"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FormateurProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="formateurs",
                        to="iot.organisation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formateur_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
