# Generated by Django 5.2.1 on 2025-12-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0002_organisation_couleur_principale_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
