# Generated by Django 5.2.1 on 2025-12-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0003_alter_organisation_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="formateurprofile",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="formateurs/photos/"
            ),
        ),
    ]
