# Generated by Django 5.2.1 on 2025-12-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0004_formateurprofile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
