# Generated by Django 5.2.1 on 2025-12-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0005_alter_organisation_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="organisations/logos/"
            ),
        ),
    ]
