# Generated by Django 5.2.1 on 2025-12-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0006_organisation_updated_at_alter_organisation_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="pdf_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
