# Generated by Django 5.2.15 on 2026-08-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_certification_pdf_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='plusieurs_reponses',
            field=models.BooleanField(default=False, help_text='Coche si cette question accepte plusieurs bonnes réponses (cases à cocher au lieu de bouton radio).'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='bonne_reponse',
            field=models.CharField(default='A', max_length=10),
        ),
    ]
