# Generated by Django 5.2.15 on 2026-08-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_quiz_plusieurs_reponses_alter_quiz_bonne_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='duree_minutes',
            field=models.PositiveIntegerField(blank=True, default=15, help_text='Temps estimé pour suivre cette leçon (théorie + pratique), en minutes.', null=True),
        ),
        migrations.AddField(
            model_name='parcours',
            name='materiel_requis',
            field=models.TextField(blank=True, help_text='Liste du matériel nécessaire pour suivre ce parcours en pratique (une ligne par élément).', null=True),
        ),
    ]
