# Generated by Django 5.2.15 on 2026-08-18 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_lecon_duree_minutes_parcours_materiel_requis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormateurFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formateurs_suivis', to=settings.AUTH_USER_MODEL)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower', 'formateur')},
            },
        ),
    ]
