# Generated by Django 5.2.15 on 2026-08-26 15:18

from django.db import migrations

DEFAULT_MODULES = [
    ("boutique", "Boutique"),
    ("tracabilite", "Traçabilité"),
    ("apprentissage", "Apprentissage"),
    ("social_feed", "Social Feed"),
    ("premium", "Premium / Monétisation"),
    ("caisse", "Scan Panier (Caisse)"),
]


def seed_modules(apps, schema_editor):
    PlatformModule = apps.get_model("iot", "PlatformModule")
    for key, name in DEFAULT_MODULES:
        PlatformModule.objects.get_or_create(key=key, defaults={"name": name, "is_published": True})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_platformmodule'),
    ]

    operations = [
        migrations.RunPython(seed_modules, noop),
    ]
