# Generated by Django 5.2.15 on 2026-08-27 00:05

from django.db import migrations

DEFAULT_MODULES = [
    ("air_quality", "Air Quality IoT"),
    ("actionneurs", "Actionneurs (Relais)"),
    ("capteurs", "Capteurs"),
    ("eclairage", "Éclairage (LED)"),
    ("surveillance_acces", "Sécurité & Surveillance"),
    ("analytics_export", "Analytics & Export"),
]


def seed_modules(apps, schema_editor):
    PlatformModule = apps.get_model("iot", "PlatformModule")
    for key, name in DEFAULT_MODULES:
        PlatformModule.objects.get_or_create(key=key, defaults={"name": name, "is_published": True})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0012_seed_platform_modules'),
    ]

    operations = [
        migrations.RunPython(seed_modules, noop),
    ]
