# Generated by Django 5.2.15 on 2026-08-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0013_seed_platform_modules_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocpedagogique',
            name='type',
            field=models.CharField(choices=[('texte', 'Texte'), ('image', 'Image'), ('video', 'Vidéo'), ('code', 'Code'), ('interactif', 'Interactif (HTML)')], max_length=20),
        ),
    ]
