"""
Django settings for monappli project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
import google.generativeai as genai

# === Gemini AI Config ===
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "AIzaSyCO8uhWDYpKD02JBoBseWOO_Qq9bzRT0UE")


LIVEKIT_API_KEY = "APIYBtxUkbTBEv9"
LIVEKIT_SECRET_KEY = "D7LQ1cGLddk76Yam248cD9e139WLkwFtefcpUBTLN1jB"
LIVEKIT_URL = "wss://founatek-live-i4dwtgab.livekit.cloud"


if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)
else:
    print("⚠️ Attention : aucune clé GEMINI_API_KEY trouvée dans les variables d'environnement.")


PAYPAL_CLIENT_ID = "Ab0m34YZToGSeyo38iFnHZHV2plHGmS-eevZl5chB9LzWPywjReAo8kLEqxRkHt5yCS-UWUP0HK4Qmpg"
PAYPAL_SECRET = "EEvDOTqc1SLLEPDbiwLuvT7JrSw5eqGroC_tlmsOkENGp1ZNEQ3vCBIioGX3MHoOD19fzINU9j3HUjXo"
PAYPAL_API_BASE = "https://api-m.sandbox.paypal.com"  # Mode test



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1au1y&pvu8#)0-gn**c1g7f(fu+rqsw_ru#9tj($8bz_y@*1nd'

import os

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['founatek224.pythonanywhere.com', 'localhost', '127.0.0.1', '10.0.2.2', '192.168.43.11']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'espcontrol',
    "iot.apps.IotConfig",  # PAS juste "iot",
    'acount',
    'eduplay',
    'product_transparency',
    'channels',
    'techfeed',
    'oscilloscope_app',
    'monetisation.apps.MonetisationConfig',
    'corsheaders',
]

#REST_FRAMEWORK = {
    #'DEFAULT_AUTHENTICATION_CLASSES': [],
    #'DEFAULT_PERMISSION_CLASSES': [
    #    'rest_framework.permissions.AllowAny',
    #]
#}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware.api_key_middleware.APIKeyMiddleware',
]

# Autoriser toutes les origines (pour tester) :
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'monappli.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.paypal_settings',
                'techfeed.context_processors.badging',
            ],
        },
    },
]



WSGI_APPLICATION = 'monappli.wsgi.application'
ASGI_APPLICATION = "monappli.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


LOGIN_REDIRECT_URL = '/home/'  # ou toute autre URL après connexion
LOGOUT_REDIRECT_URL = '/login/'  # pour revenir à la page de login après déconnexion



# settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Pour Gmail, sinon utiliser l'option appropriée
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jallohelhadjabdul@gmail.com'  # Remplace par ton email
EMAIL_HOST_PASSWORD = 'bialacjzhodegleq'  # Remplace par ton mot de passe ou utilise une application spécifique
DEFAULT_FROM_EMAIL = 'jallohelhadjabdul@gmail.com'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

#STATIC_URL = '/static/'
# Définir les URL et répertoires pour les fichiers médias
#MEDIA_URL = '/media/'  # URL de base pour accéder aux fichiers médias
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Répertoire physique où les fichiers seront stockés

# Dossier où Django va rassembler tous les fichiers statiques
#STATIC_ROOT = BASE_DIR / 'staticfiles'

# Static files (CSS, JavaScript, etc.)
STATIC_URL = '/static/'
STATIC_ROOT = '/home/Founatek224/Founatek224/staticfiles/'

# Media files (uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = '/home/Founatek224/Founatek224/media/'
VIDEO_EXTENSIONS = ['mp4', 'mov', 'avi', 'mkv']



# Paramètres d'e-mail (pour les liens de réinitialisation)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Pour tests (console)
DEFAULT_FROM_EMAIL = 'admin@founatek.com'  # Change avec ton adresse


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py

# ... tout à la fin du fichier ...
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'iot:landing'
LOGOUT_REDIRECT_URL = 'login'

# Clé Google Gemini
GEMINI_API_KEY = "AIzaSyCNNinYlYn2dJPOgv5s79MYufVC0yw8sY8"

# settings.py

# ... à la fin du fichier ...
# URL publique de l'application (scan QR)
SITE_URL = "https://founatek224.pythonanywhere.com"

FRONTEND_URL = "https://founatek224.pythonanywhere.com/product_transparency"

import os

# ... tout à la fin du fichier settings.py ...

# On crée un dossier 'cache' dans ton projet pour être sûr d'avoir les permissions
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'django_cache_folder'),
        'TIMEOUT': 60,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}