# Generated by Django 5.2.1 on 2026-04-22 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OscilloscopeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Session sans titre", max_length=200),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("wifi", "ESP32 / ESP8266 via WiFi"),
                            ("serial", "Arduino via port Série"),
                            ("sim", "Simulateur interne"),
                        ],
                        default="sim",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "sample_rate",
                    models.FloatField(
                        default=1000.0, help_text="Échantillons par seconde (Hz)"
                    ),
                ),
                (
                    "time_div",
                    models.FloatField(default=1.0, help_text="ms par division"),
                ),
                (
                    "volt_div_ch1",
                    models.FloatField(default=1.0, help_text="Volts par division CH1"),
                ),
                (
                    "volt_div_ch2",
                    models.FloatField(default=1.0, help_text="Volts par division CH2"),
                ),
                (
                    "trigger_level",
                    models.FloatField(
                        default=0.0, help_text="Niveau de déclenchement (V)"
                    ),
                ),
                ("trigger_source", models.CharField(default="CH1", max_length=4)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="osc_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeasurementSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("ch1_data", models.JSONField(blank=True, null=True)),
                ("ch2_data", models.JSONField(blank=True, null=True)),
                ("ch1_metrics", models.JSONField(blank=True, null=True)),
                ("ch2_metrics", models.JSONField(blank=True, null=True)),
                (
                    "fft_data",
                    models.JSONField(
                        blank=True, help_text="Données spectre FFT", null=True
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="oscilloscope_app.oscilloscopesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComponentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("resistor", "Résistance"),
                            ("capacitor", "Condensateur"),
                            ("inductor", "Inductance"),
                            ("diode", "Diode"),
                            ("transistor", "Transistor"),
                            ("opamp", "AOP (Amplificateur Opérationnel)"),
                            ("filter_lp", "Filtre passe-bas RC"),
                            ("filter_hp", "Filtre passe-haut RC"),
                            ("filter_bp", "Filtre passe-bande"),
                            ("rectifier", "Redresseur"),
                            ("custom", "Circuit personnalisé"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Analyse sans titre", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "component_value",
                    models.FloatField(
                        blank=True,
                        help_text="Valeur (Ω, F, H selon le composant)",
                        null=True,
                    ),
                ),
                (
                    "component_unit",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "measured_value",
                    models.FloatField(
                        blank=True, help_text="Valeur mesurée", null=True
                    ),
                ),
                (
                    "theoretical_value",
                    models.FloatField(
                        blank=True, help_text="Valeur théorique", null=True
                    ),
                ),
                ("results", models.JSONField(blank=True, null=True)),
                (
                    "bode_data",
                    models.JSONField(
                        blank=True, help_text="Données diagramme de Bode", null=True
                    ),
                ),
                ("phase_data", models.JSONField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="oscilloscope_app.oscilloscopesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(default=1, help_text="1 = CH1, 2 = CH2"),
                ),
                ("label", models.CharField(default="CH1", max_length=50)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#00ff88", "Vert"),
                            ("#00d4ff", "Cyan"),
                            ("#ffcc00", "Jaune"),
                            ("#ff4455", "Rouge"),
                            ("#ff8800", "Orange"),
                            ("#cc88ff", "Violet"),
                        ],
                        default="#00ff88",
                        max_length=10,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "offset",
                    models.FloatField(default=0.0, help_text="Décalage vertical (V)"),
                ),
                (
                    "coupling",
                    models.CharField(
                        choices=[("DC", "DC"), ("AC", "AC"), ("GND", "GND")],
                        default="DC",
                        max_length=3,
                    ),
                ),
                (
                    "probe_attn",
                    models.FloatField(
                        default=1.0, help_text="Atténuation sonde (1x, 10x, 100x)"
                    ),
                ),
                (
                    "pin",
                    models.IntegerField(
                        default=34, help_text="Pin ADC sur ESP32/Arduino"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="oscilloscope_app.oscilloscopesession",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("session", "number")},
            },
        ),
        migrations.CreateModel(
            name="SignalGenerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.IntegerField(default=1, help_text="Canal cible (1 ou 2)"),
                ),
                (
                    "wave_type",
                    models.CharField(
                        choices=[
                            ("sine", "Sinusoïdal"),
                            ("square", "Carré"),
                            ("triangle", "Triangle"),
                            ("sawtooth", "Dent de scie"),
                            ("noise", "Bruit blanc"),
                            ("pwm", "PWM"),
                            ("damped", "Sinusoïde amortie"),
                            ("am", "AM modulé"),
                        ],
                        default="sine",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.FloatField(default=100.0, help_text="Fréquence (Hz)"),
                ),
                (
                    "amplitude",
                    models.FloatField(default=3.3, help_text="Amplitude crête (V)"),
                ),
                ("offset", models.FloatField(default=0.0, help_text="Offset DC (V)")),
                ("phase", models.FloatField(default=0.0, help_text="Phase (degrés)")),
                (
                    "duty_cycle",
                    models.FloatField(
                        default=50.0, help_text="Rapport cyclique % (carré/PWM)"
                    ),
                ),
                (
                    "noise_amp",
                    models.FloatField(
                        default=0.0, help_text="Amplitude bruit ajouté (V)"
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generators",
                        to="oscilloscope_app.oscilloscopesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaveformData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_data",
                    models.JSONField(
                        help_text='Liste de valeurs [{"t": ms, "v": volts}, ...]'
                    ),
                ),
                ("sample_count", models.IntegerField(default=0)),
                (
                    "vmax",
                    models.FloatField(
                        blank=True, help_text="Tension max (V)", null=True
                    ),
                ),
                (
                    "vmin",
                    models.FloatField(
                        blank=True, help_text="Tension min (V)", null=True
                    ),
                ),
                (
                    "vpp",
                    models.FloatField(
                        blank=True, help_text="Tension crête-à-crête (V)", null=True
                    ),
                ),
                (
                    "vrms",
                    models.FloatField(
                        blank=True, help_text="Tension RMS (V)", null=True
                    ),
                ),
                (
                    "vavg",
                    models.FloatField(
                        blank=True, help_text="Tension moyenne (V)", null=True
                    ),
                ),
                (
                    "frequency",
                    models.FloatField(
                        blank=True, help_text="Fréquence (Hz)", null=True
                    ),
                ),
                (
                    "period",
                    models.FloatField(blank=True, help_text="Période (ms)", null=True),
                ),
                (
                    "duty_cycle",
                    models.FloatField(
                        blank=True, help_text="Rapport cyclique (%)", null=True
                    ),
                ),
                (
                    "rise_time",
                    models.FloatField(
                        blank=True, help_text="Temps de montée (µs)", null=True
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waveforms",
                        to="oscilloscope_app.channel",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
