# Generated by Django 5.2.1 on 2025-12-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espcontrol", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airreading",
            name="confidence",
            field=models.FloatField(
                default=0.6, help_text="Niveau de fiabilité entre 0 et 1"
            ),
        ),
        migrations.AddField(
            model_name="airreading",
            name="origin",
            field=models.CharField(
                choices=[
                    ("real", "Capteur réel"),
                    ("virtual", "Capteur virtuel"),
                    ("hybrid", "Hybride"),
                ],
                db_index=True,
                default="virtual",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="airreading",
            name="source",
            field=models.CharField(max_length=64),
        ),
    ]
