# Generated by Django 5.2 on 2025-04-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espcontrol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='led',
            old_name='state',
            new_name='etat',
        ),
    ]
