# Generated by Django 5.2.1 on 2025-12-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espcontrol", "0004_door_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="appareildata",
            name="is_anomaly",
            field=models.BooleanField(default=False),
        ),
    ]
