# Generated by Django 5.2 on 2025-04-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espcontrol', '0006_uploadedimage_delete_wasteevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Poste 1', max_length=100)),
                ('valeur', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
