# Generated by Django 5.2.1 on 2026-01-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espcontrol", "0007_sensorrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentalert",
            name="sensor",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="agentalert",
            name="value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
