# Generated by Django 5.2 on 2025-04-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espcontrol', '0007_compteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comptage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compteur', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Compteur',
        ),
    ]
