# Generated by Django 5.2 on 2025-04-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espcontrol', '0009_controle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controle',
            old_name='appareil',
            new_name='app',
        ),
    ]
