# Generated by Django 5.2.1 on 2026-05-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "espcontrol",
            "0011_device_created_at_device_latitude_device_longitude_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorrule",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("ALERT", "🚨 Alerte uniquement"),
                    (
                        "START_IRRIGATION",
                        "💧 Activer un Relais (Irrigation/Ventilation)",
                    ),
                ],
                default="ALERT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sensorrule",
            name="target_num",
            field=models.IntegerField(
                default=1, help_text="Numéro du relais à activer (1, 2, etc.)"
            ),
        ),
    ]
