# Generated by Django 5.2 on 2025-04-13 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espcontrol', '0011_appareil_programmation_delete_controle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmation',
            name='appareil',
        ),
        migrations.DeleteModel(
            name='Appareil',
        ),
        migrations.DeleteModel(
            name='Programmation',
        ),
    ]
