# Generated by Django 5.2 on 2025-04-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espcontrol', '0012_remove_programmation_appareil_delete_appareil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
