# Generated by Django 5.2 on 2025-04-13 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espcontrol', '0013_soildata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soildata',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
