# Generated by Django 5.2.15 on 2026-09-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espcontrol', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledcolor',
            name='device_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledcolor',
            name='effect',
            field=models.CharField(choices=[('fixe', 'Couleur fixe'), ('arc_en_ciel', 'Arc-en-ciel'), ('pulsation', 'Pulsation'), ('clignotant', 'Clignotant'), ('strobe', 'Strobe')], default='fixe', max_length=20),
        ),
        migrations.AddField(
            model_name='ledcolor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
