# Generated by Django 5.2.15 on 2026-09-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espcontrol', '0014_ledcolor_device_confirmed_at_ledcolor_effect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledcolor',
            name='effect',
            field=models.CharField(choices=[('fixe', 'Couleur fixe'), ('arc_en_ciel', 'Arc-en-ciel'), ('pulsation', 'Pulsation'), ('clignotant', 'Clignotant'), ('strobe', 'Strobe'), ('qualite_air', "Veilleuse qualité de l'air")], default='fixe', max_length=20),
        ),
    ]
