# Generated by Django 5.2 on 2025-05-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espcontrol', '0015_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ppm', models.FloatField()),
                ('gaz_type', models.CharField(default='inconnu', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Relais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(unique=True)),
                ('etat', models.BooleanField(default=False)),
            ],
        ),
    ]
