# Generated by Django 5.2 on 2025-04-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espcontrol", "0015_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.IntegerField(unique=True)),
                ("etat", models.BooleanField(default=False)),
            ],
        ),
    ]
