# Generated by Django 5.2.15 on 2026-10-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espcontrol', '0017_chatlog_proactive_chatlog_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5),
        ),
    ]
