# Generated by Django 5.2 on 2025-05-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduplay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.AddField(
            model_name='question',
            name='multiple_answers',
            field=models.BooleanField(default=False),
        ),
    ]
