# Generated by Django 5.2 on 2025-05-06 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduplay', '0002_remove_question_created_at_question_multiple_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 6, 15, 28, 37, 23200, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
