# Generated by Django 5.2.1 on 2025-08-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eduplay", "0005_useranswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="attempt",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
