# Generated by Django 5.2.1 on 2025-08-05 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eduplay", "0007_arduinouseranswer_electrouseranswer_iotuseranswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arduinouseranswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="eduplay.arduinoquestion",
            ),
        ),
        migrations.AlterField(
            model_name="electrouseranswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="eduplay.electroniquequestion",
            ),
        ),
        migrations.AlterField(
            model_name="iotuseranswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eduplay.iotquestion"
            ),
        ),
    ]
