# Generated by Django 5.2.1 on 2025-12-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_transparency", "0003_company_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
