# Generated by Django 5.2.1 on 2025-12-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_transparency", "0004_company_logo_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="currency",
            field=models.CharField(
                choices=[
                    ("GNF", "Franc guinéen (GNF)"),
                    ("XOF", "Franc CFA (XOF)"),
                    ("USD", "Dollar américain (USD)"),
                    ("EUR", "Euro (EUR)"),
                ],
                default="GNF",
                max_length=3,
            ),
        ),
    ]
