# Generated by Django 5.2.15 on 2026-08-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_transparency', '0006_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text='Quantité en stock. Laisser vide pour ne pas suivre le stock (vente illimitée).', null=True),
        ),
    ]
